apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: chatroom-app-client
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: SERVER_URL
          value: "http://server:8080"
        - name: PORT
          value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 3000 # Expose on port 80
    targetPort: 3000
    nodePort: 30007
  type: NodePort # Expose the service using NodePort
