apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: chatroom-app-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URL
          value: "mongodb://database:27017/ChatRoomDB"
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        - name: WORKERS
          value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
